extends Node

var driver_names: Dictionary = {
	"PIA": "Oscar Piastri",
	"NOR": "Lando Norris",
	"LEC": "Charles Leclerc",
	"HAM": "Lewis Hamilton",
	"RUS": "George Russell",
	"ANT": "Kimi Antonelli",
	"VER": "Max Verstappen",
	"TSU": "Yuki Tsunoda",
	"ALB": "Alexander Albon",
	"SAI": "Carlos Sainz",
	"STR": "Lance Stroll",
	"ALO": "Fernando Alonso",
	"HUL": "Nico Hulkenburg",
	"BOR": "Gabriel Bortoleto",
	"LAW": "Liam Lawson",
	"HAD": "Isack Hadjar",
	"OCO": "Esteban Ocon",
	"BEA": "Oliver Bearman",
	"GAS": "Pierre Gasly",
	"COL": "Franco Colapinto",
}

var driver_images: Dictionary = {
	"PIA": "res://assets/drivers/pia.png",
	"NOR": "res://assets/drivers/nor.png",
	"LEC": "res://assets/drivers/lec.png",
	"HAM": "res://assets/drivers/ham.png",
	"RUS": "res://assets/drivers/rus.png",
	"ANT": "res://assets/drivers/ant.png",
	"VER": "res://assets/drivers/ver.png",
	"TSU": "res://assets/drivers/tsu.png",
	"ALB": "res://assets/drivers/alb.png",
	"SAI": "res://assets/drivers/sai.png",
	"STR": "res://assets/drivers/str.png",
	"ALO": "res://assets/drivers/alo.png",
	"HUL": "res://assets/drivers/hul.png",
	"BOR": "res://assets/drivers/bor.png",
	"LAW": "res://assets/drivers/law.png",
	"HAD": "res://assets/drivers/had.png",
	"OCO": "res://assets/drivers/oco.png",
	"BEA": "res://assets/drivers/bea.png",
	"GAS": "res://assets/drivers/gas.png",
	"COL": "res://assets/drivers/col.png",
}
