extends Node

var track_data_collection: Dictionary = {
	"DLS": {
		"track_image": "res://assets/circuits/dls.png",
		"total_laps": 10,
		"lap_step_length": 100,
		"pit_step_length": 10,
		"pit_entry_point": 1,
		"pit_exit_point": 1,
		"pit_stoppage_point": 1,
	},
	"AUS": {
		"track_image": "res://assets/circuits/aus.svg",
		"total_laps": 18,
		"lap_step_length": 5268,
		"pit_step_length": 1158,
		"pit_entry_point": 4714,
		"pit_exit_point": 242,
		"pit_stoppage_point": 728,
	},
	"CHI": {
		"track_image": "res://assets/circuits/chi.svg",
		"total_laps": 16,
		"lap_step_length": 6088,
		"pit_step_length": 1340,
		"pit_entry_point": 5580,
		"pit_exit_point": 320,
		"pit_stoppage_point": 774,
	},
	"JPN": {
		"track_image": "res://assets/circuits/jpn.svg",
		"total_laps": 16,
		"lap_step_length": 6004,
		"pit_step_length": 1320,
		"pit_entry_point": 5438,
		"pit_exit_point": 230,
		"pit_stoppage_point": 792,
	},
	"BHR": {
		"track_image": "res://assets/circuits/bhr.svg",
		"total_laps": 16,
		"lap_step_length": 6036,
		"pit_step_length": 1328,
		"pit_entry_point": 5454,
		"pit_exit_point": 372,
		"pit_stoppage_point": 690,
	},
	"SAU": {
		"track_image": "res://assets/circuits/sau.png",
		"total_laps": 16,
		"lap_step_length": 5988,
		"pit_step_length": 1318,
		"pit_entry_point": 5484,
		"pit_exit_point": 528,
		"pit_stoppage_point": 796,
	},
	"MIA": {
		"track_image": "res://assets/circuits/mia.svg",
		"total_laps": 16,
		"lap_step_length": 5920,
		"pit_step_length": 1302,
		"pit_entry_point": 5434,
		"pit_exit_point": 410,
		"pit_stoppage_point": 782,
	},
	"EMI": {
		"track_image": "res://assets/circuits/emi.svg",
		"total_laps": 19,
		"lap_step_length": 4982,
		"pit_step_length": 1096,
		"pit_entry_point": 4740,
		"pit_exit_point": 592,
		"pit_stoppage_point": 406,
	},
	"MON": {
		"track_image": "res://assets/circuits/mon.svg",
		"total_laps": 20,
		"lap_step_length": 4812,
		"pit_step_length": 1058,
		"pit_entry_point": 4276,
		"pit_exit_point": 96,
		"pit_stoppage_point": 634,
	},
	"ESP": {
		"track_image": "res://assets/circuits/esp.png",
		"total_laps": 19,
		"lap_step_length": 5000,
		"pit_step_length": 1100,
		"pit_entry_point": 4394,
		"pit_exit_point": 488,
		"pit_stoppage_point": 526,
	},
	"CAN": {
		"track_image": "res://assets/circuits/can.svg",
		"total_laps": 20,
		"lap_step_length": 4824,
		"pit_step_length": 1062,
		"pit_entry_point": 4350,
		"pit_exit_point": 448,
		"pit_stoppage_point": 492,
	},
	"AUT": {
		"track_image": "res://assets/circuits/aut.svg",
		"total_laps": 22,
		"lap_step_length": 4482,
		"pit_step_length": 986,
		"pit_entry_point": 3976,
		"pit_exit_point": 614,
		"pit_stoppage_point": 546,
	},
	"GBR": {
		"track_image": "res://assets/circuits/gbr.png",
		"total_laps": 17,
		"lap_step_length": 5748,
		"pit_step_length": 1264,
		"pit_entry_point": 5170,
		"pit_exit_point": 592,
		"pit_stoppage_point": 770,
	},
	"BEL": {
		"track_image": "res://assets/circuits/bel.svg",
		"total_laps": 14,
		"lap_step_length": 6910,
		"pit_step_length": 1520,
		"pit_entry_point": 6720,
		"pit_exit_point": 552,
		"pit_stoppage_point": 776,
	},
	"HUN": {
		"track_image": "res://assets/circuits/hun.svg",
		"total_laps": 19,
		"lap_step_length": 5058,
		"pit_step_length": 1112,
		"pit_entry_point": 4532,
		"pit_exit_point": 588,
		"pit_stoppage_point": 616,
	},
	"NED": {
		"track_image": "res://assets/circuits/ned.png",
		"total_laps": 21,
		"lap_step_length": 4692,
		"pit_step_length": 1032,
		"pit_entry_point": 4418,
		"pit_exit_point": 584,
		"pit_stoppage_point": 524,
	},
	"ITA": {
		"track_image": "res://assets/circuits/ita.svg",
		"total_laps": 18,
		"lap_step_length": 5340,
		"pit_step_length": 1174,
		"pit_entry_point": 5140,
		"pit_exit_point": 568,
		"pit_stoppage_point": 504,
	},
	"AZE": {
		"track_image": "res://assets/circuits/aze.svg",
		"total_laps": 14,
		"lap_step_length": 5340,
		"pit_step_length": 1174,
		"pit_entry_point": 5010,
		"pit_exit_point": 434,
		"pit_stoppage_point": 684,
	},
	"SIN": {
		"track_image": "res://assets/circuits/sin.svg",
		"total_laps": 15,
		"lap_step_length": 6236,
		"pit_step_length": 1372,
		"pit_entry_point": 5816,
		"pit_exit_point": 648,
		"pit_stoppage_point": 784,
	},
	"USA": {
		"track_image": "res://assets/circuits/usa.svg",
		"total_laps": 15,
		"lap_step_length": 6348,
		"pit_step_length": 1396,
		"pit_entry_point": 5922,
		"pit_exit_point": 656,
		"pit_stoppage_point": 758,
	},
	"MXC": {
		"track_image": "res://assets/circuits/mxc.svg",
		"total_laps": 19,
		"lap_step_length": 5134,
		"pit_step_length": 1130,
		"pit_entry_point": 4586,
		"pit_exit_point": 378,
		"pit_stoppage_point": 550,
	},
	"SAP": {
		"track_image": "res://assets/circuits/sap.svg",
		"total_laps": 21,
		"lap_step_length": 4656,
		"pit_step_length": 1024,
		"pit_entry_point": 4084,
		"pit_exit_point": 890,
		"pit_stoppage_point": 392,
	},
	"LVG": {
		"track_image": "res://assets/circuits/lvg.svg",
		"total_laps": 15,
		"lap_step_length": 6262,
		"pit_step_length": 1378,
		"pit_entry_point": 6032,
		"pit_exit_point": 424,
		"pit_stoppage_point": 758,
	},
	"QAT": {
		"track_image": "res://assets/circuits/qat.svg",
		"total_laps": 18,
		"lap_step_length": 5438,
		"pit_step_length": 1196,
		"pit_entry_point": 5082,
		"pit_exit_point": 616,
		"pit_stoppage_point": 608,
	},
	"ABU": {
		"track_image": "res://assets/circuits/abu.png",
		"total_laps": 17,
		"lap_step_length": 5652,
		"pit_step_length": 1244,
		"pit_entry_point": 5342,
		"pit_exit_point": 870,
		"pit_stoppage_point": 440,
	},
}

func send_track_data(track: String) -> Dictionary:
	return track_data_collection[track]
